services:
  # --- BASE DE DATOS POSTGRESQL ---
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=andres
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=my_store
    ports:
      - "5432:5432"
    volumes:
      # Tus datos de Postgres se guardan en la carpeta local 'postgres_data'
      - ./postgres_data:/var/lib/postgresql/data

  # --- ADMINISTRADOR DE POSTGRES (pgAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    volumes:
      # CAMBIO CLAVE: Volumen para que pgAdmin guarde tus servidores registrados y contraseñas
      - pgadmin_data:/var/lib/pgadmin

  # --- BASE DE DATOS MYSQL ---
  mysql:
    image: mysql:8
    # Mantiene compatibilidad con procesadores modernos (M1/M2/Intel)
    platform: linux/amd64 
    environment:
      - MYSQL_DATABASE=my_store
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_USER=andres
      - MYSQL_PASSWORD=admin123
    ports:
      - "3306:3306"
    volumes:
      # Los datos de MySQL se guardan en la carpeta local 'mysql_data'
      - ./mysql_data:/var/lib/mysql

  # --- ADMINISTRADOR DE MYSQL (phpMyAdmin) ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    environment:
      - PMA_HOST=mysql # Se conecta al servicio llamado 'mysql' arriba definido
      - PMA_USER=root
      - PMA_PASSWORD=admin123
    ports:
      - "8080:80"
    depends_on:
      - mysql

# DEFINICIÓN DE VOLÚMENES NOMBRADOS
volumes:
  # Este volumen es el que permite que pgAdmin "recuerde" tus servidores
  pgadmin_data: